version: '3'
services:
  web:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - API_KEY=YOUR_API_KEY_HERE
    depends_on:
      - redis
      - db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'audiotekon_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
