version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"